SET DEFINE OFF;

DROP TABLE order_details;

DROP TABLE product_images;

DROP TABLE orders;

DROP TABLE products;

DROP TABLE categories;

DROP TABLE tokens;

DROP TABLE social_accounts;

DROP TABLE users;

DROP TABLE roles;

CREATE TABLE roles(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name NVARCHAR2(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT chk_name_roles CHECK (name IN ('admin','user'))
);

INSERT INTO roles (name) VALUES ('admin');
INSERT INTO roles (name) VALUES ('user');

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    phone_number NVARCHAR2(255) NOT NULL ,
    password NVARCHAR2(255) NOT NULL ,
    fullname NVARCHAR2(255) DEFAULT '',
    address NVARCHAR2(255) DEFAULT '',
    is_active NUMBER(1) DEFAULT 1,
    created_at DATE,
    updated_at DATE,
    date_of_birth DATE,
    facebook_account_id NUMBER DEFAULT 0,
    google_account_id NUMBER DEFAULT 0,
    role_id NUMBER NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT phone_number UNIQUE (phone_number),
    CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES roles(id)
);

INSERT INTO users(phone_number,password,fullname,address,role_id) VALUES ('0987654321','$2a$10$OK0gQxDSMaBXN6f8rdIqYu8U/ebzue7Px8tRhRQ0xYS6vpA0bNWH6','Nguyen Nhat Minh','HN',2);
INSERT INTO users(phone_number,password,fullname,address,role_id) VALUES ('123456789','$2a$10$OK0gQxDSMaBXN6f8rdIqYu8U/ebzue7Px8tRhRQ0xYS6vpA0bNWH6','Nguyen Nhat Ha','HN',2);
INSERT INTO users(phone_number,password,fullname,address,role_id) VALUES ('000000000','$2a$10$OK0gQxDSMaBXN6f8rdIqYu8U/ebzue7Px8tRhRQ0xYS6vpA0bNWH6','admin','HN',1);

CREATE TABLE tokens(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    token VARCHAR2(255) UNIQUE NOT NULL,
    token_type VARCHAR2(255) NOT NULL,
    expiration_date DATE,
    revoked NUMBER(1) NOT NULL,
    expired NUMBER(1) NOT NULL,
    refresh_token VARCHAR2(255) NOT NULL,
    refresh_expiration_date DATE,
    user_id NUMBER,
    PRIMARY KEY (id),
    CONSTRAINT fk_user_id_tokens FOREIGN KEY(user_id) REFERENCES users(id)
);

--hỗ trợ đăng nhập từ Faceproduct và Google
CREATE TABLE social_accounts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    provider VARCHAR2(20) NOT NULL,
    provider_id VARCHAR2(50) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    user_id NUMBER,
    CONSTRAINT fk_social_accounts_user_id
        FOREIGN KEY (user_id)
        REFERENCES users (id)
);

--Bảng danh mục sản phẩm(Category)
CREATE TABLE categories(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name NVARCHAR2(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO categories(name) VALUES('Đồ điện tử');
INSERT INTO categories(name) VALUES('Đồ gia dụng');
INSERT INTO categories(name) VALUES('Phụ kiện');


CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name NVARCHAR2(255) NOT NULL,
    price NUMBER NOT NULL CHECK (price >= 0),
    thumbnail VARCHAR2(255)  DEFAULT '',
    description CLOB  DEFAULT '',
    created_at DATE,
    updated_at DATE,
    category_id NUMBER,
    PRIMARY KEY (id),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE product_images (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER,
    CONSTRAINT fk_product_images_product_id
        FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE CASCADE,
    image_url VARCHAR2(300),
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    fullname NVARCHAR2(255) DEFAULT '',
    email VARCHAR2(255) DEFAULT '',
    phone_number VARCHAR2(255) NOT NULL,
    address NVARCHAR2(255) NOT NULL,
    note VARCHAR2(255) DEFAULT '',
    order_date DATE DEFAULT SYSDATE,
    status VARCHAR2(255) DEFAULT'pending',
    total_money NUMBER CHECK (total_money >= 0),
    active NUMBER(1) DEFAULT 1,
    shipping_method VARCHAR2(255),
    payment_method VARCHAR2(255),
    shipping_date DATE,
    shipping_address VARCHAR2(255),
    tracking_number VARCHAR2(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_orders_status CHECK (status IN ('pending', 'processing', 'shipped', 'cancelled','deliverd'))
);

    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'John Smith', 'john@example.com', '1234567890', '123 Main St', 'Note 1', 'pending', 500);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Eric Thompson', 'eric@example.com', '9876143210', '416 Elm St', 'Note 2', 'pending', 400);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Hans', 'hans@example.com', '1111111111', '789 Oak St', 'Note 3', 'pending', 300);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Alice Johnson', 'alice@example.com', '1111234167', '789 Cherry Ave', 'Note 4', 'pending', 200);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Robert Williams', 'robert@example.com', '1119876143', '321 Maple Rd', 'Note 1', 'pending', 100);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Sarah Davis', 'sarah@example.com', '1114441111', '987 Elm St', 'Note 6', 'pending', 210);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Michael Anderson', 'michael@example.com', '1116667777', '614 Oak Ave', 'Note 7', 'pending', 310);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Emma Wilson', 'emma@example.com', '1118889999', '789 Maple Ln', 'Note 8', 'pending', 410);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Olivia Brown', 'olivia@example.com', '1111112222', '987 Pine St', 'Note 47', 'pending', 310);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'William Davis', 'william@example.com', '1113334444', '614 Elm Ave', 'Note 48', 'pending', 210);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Sophia Wilson', 'sophia@example.com', '1111116666', '789 Oak Ln', 'Note 49', 'pending', 110);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Alexander Anderson', 'alexander@example.com', '1117778888', '416 Maple Lane', 'Note 10', 'pending', 410);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Ava Thompson', 'ava@example.com', '1119990000', '987 Walnut Rd', 'Note 11', 'pending', 110);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Daniel Johnson', 'daniel@example.com', '1112223333', '614 Pine Ave', 'Note 12', 'pending', 610);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Mia Williams', 'mia@example.com', '1114441111', '789 Elm St', 'Note 13', 'pending', 710);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'James Davis', 'james@example.com', '1116667777', '416 Oak Ave', 'Note 14', 'pending', 810);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Benjamin Thompson', 'benjamin@example.com', '1110001111', '614 Walnut Rd', 'Note 16', 'pending', 110);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Sophia Anderson', 'sophia@example.com', '1111112222', '987 Pine St', 'Note 17', 'pending', 310);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Elijah Davis', 'elijah@example.com', '1113334444', '614 Elm Ave', 'Note 18', 'pending', 210);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Ava Wilson', 'ava@example.com', '1111116666', '789 Oak Ln', 'Note 19', 'pending', 110);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Oliver Thompson', 'oliver@example.com', '1117778888', '416 Maple Lane', 'Note 60', 'pending', 410);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Mia Johnson', 'mia@example.com', '1119990000', '987 Walnut Rd', 'Note 61', 'pending', 110);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'James Williams', 'james@example.com', '1112223333', '614 Pine Ave', 'Note 62', 'pending', 610);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Charlotte Davis', 'charlotte@example.com', '1114441111', '789 Elm St', 'Note 63', 'pending', 710);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Benjamin Wilson', 'benjamin@example.com', '1116667777', '416 Oak Ave', 'Note 64', 'pending', 810);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (2, 'Amelia Thompson', 'amelia@example.com', '1118889999', '321 Maple Ln', 'Note 61', 'pending', 910);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Henry Johnson', 'henry@example.com', '1110001111', '614 Walnut Rd', 'Note 66', 'pending', 110);
    INSERT INTO orders (user_id, fullname, email, phone_number, address, note, status, total_money) VALUES
    (1, 'Emily Davis', 'emily@example.com', '1112223333', '416 Walnut Lane', 'Note 46', 'pending', 110);

CREATE TABLE order_details (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id NUMBER,
    product_id NUMBER,
    price NUMBER NOT NULL CHECK (price >= 0),
    number_of_products NUMBER NOT NULL CHECK (number_of_products >= 0),
    total_money NUMBER NOT NULL CHECK (total_money >= 0),
    CONSTRAINT fk_order_id FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (14, 1, 10.99, 2, 21.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (14, 2, 1.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (14, 3, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (11, 1, 10.99, 2, 21.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (15, 2, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (15, 3, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (16, 6, 12.99, 3, 38.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (17, 7, 6.99, 1, 6.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (18, 8, 14.99, 2, 29.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (19, 9, 11.49, 1, 11.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (20, 10, 8.99, 3, 26.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (21, 11, 13.99, 2, 27.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (22, 12, 10.49, 1, 10.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (23, 13, 7.49, 2, 14.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (8, 1, 10.99, 2, 21.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (8, 2, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (8, 3, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (24, 14, 9.99, 2, 19.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (24, 15, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (24, 16, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (25, 17, 10.99, 2, 21.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (25, 18, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (25, 19, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (26, 20, 6.99, 2, 13.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (26, 21, 14.99, 1, 14.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (26, 22, 11.49, 3, 34.47);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (27, 23, 8.99, 2, 17.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (27, 24, 13.99, 1, 13.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (27, 25, 10.49, 3, 31.47);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (28, 26, 7.49, 2, 14.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (28, 27, 9.99, 1, 9.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (28, 28, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (9, 29, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (9, 30, 10.99, 2, 21.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (9, 31, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (10, 32, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (10, 33, 6.99, 2, 13.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (10, 34, 14.99, 1, 14.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (1, 15, 11.49, 3, 34.47);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (1, 16, 8.99, 2, 17.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (1, 37, 13.99, 1, 13.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (2, 38, 10.49, 3, 31.47);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (2, 39, 7.49, 2, 14.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (2, 40, 9.99, 1, 9.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (3, 41, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (3, 42, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (3, 43, 10.99, 2, 21.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (4, 44, 5.99, 3, 17.97);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (4, 45, 8.49, 1, 8.49);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (4, 46, 6.99, 2, 13.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (15, 47, 14.99, 1, 14.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (15, 48, 11.49, 3, 34.47);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (15, 49, 8.99, 2, 17.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (16, 50, 13.99, 1, 13.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (16, 51, 10.49, 3, 31.47);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (16, 52, 7.49, 2, 14.98);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (17, 53, 9.99, 1, 9.99);
    INSERT INTO order_details (order_id, product_id, price, number_of_products, total_money) VALUES
    (17, 54, 5.99, 3, 17.97);


