server:
    port : 80

api:
    prefix: api/v1

spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:oracle:thin:@192.168.1.2:1521:orcl
    username: minh
    password: minhpro
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      use-redis-cache : true
      host: redis
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt: 
    expiration : 2592000 #30days
    expiration-refresh-token: 5184000 #60days
    secretKey : /VAQau69iENaScwR1N3QWyJxUBxW+iJ1NnAnj9jMBBI=
    
logging:
  level:
    # org.hibernate.orm.jdbc.bind: trace
    # org.hibernate.SQL: debug
    # org.hibernate.type: TRACE
    # org.hibernate.type.descriptor.sql: trace
    # org.springframework.security: debug
    # org.springframework.web: debug
    com.shopapp.components.ApiLoggingFilter: DEBUG
  
management:
  endpoints:
    web:
      base-path: /api/v1
      exposure:
        include: "health, info"
  endpoint:
    health:
      show-details: always